### ISSUE TITLE
Date tweaks

### ISSUE THREAD

**Issue by pjthorman** [jiscdev/study-goal-android#1]
Hi just looked today and instead of showing January 31st, it's displaying January 31th. 

The same applies to 23rd (23th displays) and 22nd (22th), 21st (21th).

1st and 2nd and 3rd are correct.

**Comment by tomglanville** [comment]
Has this now been fixed?

**Comment by mparker-tbox** [comment]
Hi Tom,

 

This was resolved on the highcharts branch, but we can also fix in develop if the highcharts switch isn’t happening anytime shortly.

 

Kind regards,

 

Matthew Parker

Business Analyst

email.  <mailto:cflomet@therapy-box.co.uk> mparker@therapy-box.co.uk | phone.  +44 (0)208 7493474 | fax. +44 (0)208 7113646 | website.  <http://www.therapy-box.co.uk/> www.therapy-box.co.uk

**Comment by mparker-tbox** [comment]
Fixed in highcharts branch, but can also add a fix into develop if that's preferred.

**Comment by tomglanville** [comment]
That would be good as unsure when highcharts will be merged in.

**Comment by pjthorman** [comment]
Still happening for 21st, 22nd, 23rd, 31st on my Samsung Galaxy S6 (Android 6.0.1) v5.0 SG. Logged 4 retrospective events for Mar / Apr. See screenshots. 
![21st fw](https://cloud.githubusercontent.com/assets/25012528/25906043/8c1cf610-359b-11e7-95ef-ad31257cad66.png)
![22nd fw](https://cloud.githubusercontent.com/assets/25012528/25906046/8e9485de-359b-11e7-8575-b44e0382ec91.png)
![23rd fw](https://cloud.githubusercontent.com/assets/25012528/25906048/90ee6dae-359b-11e7-9305-64b028a9c312.png)
![31st fw](https://cloud.githubusercontent.com/assets/25012528/25906055/9304d790-359b-11e7-9b85-61b5ad333883.png)

**Comment by tomglanville** [comment]
Hi - is this still an issue? If so it would be good to move it into the main github issues repo: https://github.com/jiscdev/study-goal/issues

**Comment by tomglanville** [comment]
Working on develop.

**Comment by pjthorman** [comment]
Hi Tom

I can’t find the ticket or github item that relates, but I’ve checked again today and see attached – still puts ‘th’ instead of ‘nd’ after 22.

Also clicked on date to edit to see if the other problem numbers like 21st and 23rd still show as ‘th’ but when the calendar pops up and you select the alternative date, the calendar remains in view, no change occurs.

Same Android phone S6 (SM-G920F)as last time, Android V7.0

Phil

**Comment by tomglanville** [comment]
Hi Phil - can you send again I didn't receive the attachment. Also what branch are you testing on? If this is still an issue I'll need to move it to the main [github issues page](https://github.com/jiscdev/study-goal/issues) for Study Goal.
